import "../../app/global.css"; // Import global CSS
import AdminLayoutClient from "./AdminLayoutClient";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // Import CSS cho toast
import "@ant-design/v5-patch-for-react-19";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="vi">
      <body>
        {/* Gọi đến component client */}
        <AdminLayoutClient>{children}</AdminLayoutClient>

        {/* Thêm ToastContainer để hiển thị thông báo toast */}
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
